#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Define The Loader Path
|--------------------------------------------------------------------------
|
| The NewUp utility provides loaders that will auto-magically load
| package information and add it to Composer's autoload at run-
| time. We just need to tell the NewUp core framework where
| to find Composer's auto-loader.
|
*/
define('NEWUP_LOADER_PATH', __DIR__.'/vendor/autoload.php');

/*
|--------------------------------------------------------------------------
| Define The Utility Path
|--------------------------------------------------------------------------
|
| The NewUp utility utilizes Composer to do self updates. Because
| of this, we need to tell the core utility framework where to
| run the "composer update" command. Makes updates easier!
|
*/
define('NEWUP_UTILITY_PATH', __DIR__);

$userConfigurationPath = '';

if (getenv('NEWUP_CONFIGURATION') !== false) {
    // Allow a user to set the configuration path using a system variable.
    $userConfigurationPath = getenv('NEWUP_CONFIGURATION');
} elseif (file_exists(__DIR__.'/config')) {
    // This file will be present if running NewUp directly.
    $userConfigurationPath = __DIR__.'/config';
}

define('NEWUP_CORE_USER_CONFIGURATION_DIRECTORY', $userConfigurationPath);

/*
|--------------------------------------------------------------------------
| Start The Utility
|--------------------------------------------------------------------------
|
| The "NewUp\NewUp" utility is essentially a wrapper around
| the core framework's utility. We will just return the
| result of the core utility so we don't have to redo
| all the commands in this utility. Sneaky.
|
*/
return include __DIR__.'/vendor/newup/core/newup.php';