#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Define The Loader Path
|--------------------------------------------------------------------------
|
| The NewUp utility provides loaders that will auto-magically load
| package information and add it to Composer's autoload at run-
| time. We just need to tell the NewUp core framework where
| to find Composer's auto-loader.
|
*/
define('NEWUP_LOADER_PATH', __DIR__.'/newup_vendor/autoload.php');

/*
|--------------------------------------------------------------------------
| Define The Utility Path
|--------------------------------------------------------------------------
|
| The NewUp utility utilizes Composer to do self updates. Because
| of this, we need to tell the core utility framework where to
| run the "composer update" command. Makes updates easier!
|
*/
define('NEWUP_UTILITY_PATH', __DIR__);


/*
|--------------------------------------------------------------------------
| Copy The User Configuration Files
|--------------------------------------------------------------------------
|
| The NewUp core utility allows end-users to configure various
| behavioral aspects using configuration files. However, we
| need to copy the contents of the 'config' directory to
| the utilities user configuration directory. This will
| allow all the changes to stay in sync even between
| Composer updates, even if it seems like a hack.
|
*/
define('NEWUP_CORE_USER_CONFIGURATION_DIRECTORY', __DIR__.'/newup_vendor/newup/core/config/user/');
define('NEWUP_UTILITY_USER_CONFIGURATION_DIRECTORY', __DIR__.'/config/');

foreach (glob(NEWUP_UTILITY_USER_CONFIGURATION_DIRECTORY.'*.php') as $configurationFile) {
    if (!is_dir($configurationFile) && is_readable($configurationFile)) {
        $utilityPath = NEWUP_CORE_USER_CONFIGURATION_DIRECTORY.DIRECTORY_SEPARATOR.basename($configurationFile);
        copy($configurationFile, $utilityPath);
    }
}

/*
|--------------------------------------------------------------------------
| Start The Utility
|--------------------------------------------------------------------------
|
| The "NewUp\NewUp" utility is essentially a wrapper around
| the core framework's utility. We will just return the
| result of the core utility so we don't have to redo
| all the commands in this utility. Sneaky.
|
*/
return include __DIR__.'/newup_vendor/newup/core/newup.php';